version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobeasy
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mobeasy-network

  api:
    image: mobeasy-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mobeasy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      LOG_LEVEL: info
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mobeasy-network

volumes:
  db_data:

networks:
  mobeasy-network:
    driver: bridge