server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mobeasy}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: Mobeasy API

springdoc:
  swagger-ui:
    tagsSorter: method         # Tri des tags par ordre alphabétique
    operationsSorter: method   # Tri des opérations par ordre alphabétique


logging:
  level:
    org:
      hibernate:
        SQL: info
      springframework:
        jdbc:
          core: info
        security: ${LOG_LEVEL:info}
    root: ${LOG_LEVEL:debug}

jwt:
  secret: yCEejd7w8gmc2LO4iv6vZYYW9yL2p1i3za9Fhm9ZdN2MmkFQ39t0RCWoOjC8TOnMNzH8fFVGKU6xffDYciRnAFTfakY8orzK6ShGlwJEnW4Ok9oHFUKx0XSTOrl14Ixa
  expiration: 86400000
